# 心理测试平台 - 基础服务 Docker Compose 配置
# 仅包含 PostgreSQL 和 Redis 服务，用于本地开发

services:
  # PostgreSQL 数据库服务
  postgres:
    image: postgres:15-alpine
    container_name: psychology-test-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-psychology_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-psychology_password}
      POSTGRES_DB: ${POSTGRES_DB:-psychology_test_db}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-psychology_user} -d ${POSTGRES_DB:-psychology_test_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: psychology-test-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local